name: Codes – Assign (toewijzen aan dealer)
description: Wijs codes toe aan een dealer; kies specifieke codes of een hoeveelheid.
title: "[Codes] Assign — <dealer>"
labels: ["beheer", "codes:assign"]
body:
  - type: input
    id: dealer
    attributes:
      label: Dealer ID
      placeholder: dealer-001
    validations:
      required: true
  - type: input
    id: amount
    attributes:
      label: Aantal codes toe te wijzen
      placeholder: "1"
  - type: input
    id: expires
    attributes:
      label: Vervaldatum (dd-mm-jjjj, optioneel)
      placeholder: "31-12-2026"
  - type: textarea
    id: fixed
    attributes:
      label: Specifieke bestaande codes (optioneel, één per regel)
      placeholder: |
        FSID-ABCD-EFGH-IJKL
        FSID-MNOP-QRST-UVWX
