name: Codes – Release (vrijmaken)
description: Maak toegewezen codes weer vrij (issued_to → null).
title: "[Codes] Release — <dealer of codes>"
labels: ["beheer", "codes:release"]
body:
  - type: input
    id: dealer
    attributes:
      label: Dealer ID (optioneel)
      placeholder: dealer-001
  - type: dropdown
    id: all_codes
    attributes:
      label: Alle codes van dealer? (ja/nee)
      options: ["nee", "ja"]
  - type: textarea
    id: codes
    attributes:
      label: Specifieke bestaande codes (optioneel, één per regel)
      placeholder: |
        FSID-ABCD-EFGH-IJKL
        FSID-MNOP-QRST-UVWX
