name: Dealer beheren
description: Voeg een dealer toe of werk gegevens bij.
title: "[Dealer] Toevoegen/bijwerken"
labels: ["beheer", "dealer:upsert"]
body:
  - type: input
    id: dealer_id
    attributes:
      label: Dealer ID
      placeholder: bv. dealer-001
    validations:
      required: true
  - type: input
    id: naam
    attributes:
      label: Naam
      placeholder: bv. Fiets Service Axel
    validations:
      required: true
  - type: input
    id: email
    attributes:
      label: E-mail
  - type: input
    id: telefoon
    attributes:
      label: Telefoon
  - type: textarea
    id: adres
    attributes:
      label: Adres (JSON)
      description: |
        Geef adres als JSON, bv:
        {"straat":"Voorbeeldstraat 1","postcode":"4571 AA","plaats":"Axel","land":"NL"}
  - type: textarea
    id: notities
    attributes:
      label: Notities
